name: nodejs.ci(pnpm)

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 30 # タイムアウト時間を30分に設定
    runs-on: ubuntu-latest
    steps:
      # ステップ１: リポジトリのコードを取得
      - uses: actions/checkout@v6
      # ステップ２: pnpmをインストール
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      # ステップ３: Node.jsのセットアップ
      - name: Use Nodejs LTS
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "pnpm"
      # ステップ４: 依存関係のインストール
      - name: Install dependencies
        run: pnpm install
      # ステップ５: Next.jsビルドキャッシュの設定
      - name: Cache Next.js build
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.next/cache
          # パッケージまたはソースファイルが変更されるたびに新しいキャッシュを生成
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # ソースファイルが変更されたがパッケージが変更されていない場合、以前のキャッシュから再構築
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      # ステップ６: Playwrightブラウザのインストール
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      # ステップ７: nextjsのビルド
      - name: Build Next.js application
        run: pnpm build
      # ステップ８: Playwrightテストの実行
      - name: Run Playwright tests
        run: pnpm exec playwright test
      # ステップ９: Playwrightレポートのアップロード
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
